[env:m5stick-c-plus2]
platform = platformio/espressif32
board = m5stickc_plus2
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 115200
upload_speed = 1500000
build_flags = 
	-Iinclude
	-Isystem
	-Wl,-zmuldefs

lib_deps = 
	m5stack/M5Unified
	m5stack/M5GFX
	adafruit/Adafruit PN532@^1.1.0
	https://github.com/blackketter/ESP32-BLE-Combo.git
	dfrobot/DFRobot_GP8XXX @ 1.0.1
upload_port = COM3


; The project needs to be adapted for emulation
[env:native]
platform = native
build_type = debug
build_flags = 
	-O0 -std=c++14
	-I/ucrt64/include/SDL2
	-L/ucrt64/lib
	-lmingw32 -lSDL2main -lSDL2
	-mwindows
	-DM5GFX_SHOW_FRAME
	-DM5GFX_BOARD=board_M5StickCPlus
	-DM5GFX_SCALE=2
	-DEMULATION=1
lib_deps = 
	m5stack/M5Unified
	m5stack/M5GFX
lib_ignore = 
	WiFi