#include "../functions/mainMenuLoop.h"
#include "../functions/settingsLoop.h"
#include "../functions/clockLoop.h"
#include "../functions/batteryLoop.h"
#include "../functions/brightnessLoop.h"
#include "../functions/rotationLoop.h"
#include "../functions/statusBarLoop.h"
#include "../functions/wifiApLoop.h"