// All files from the functions/ folder
#include "../functions/defaultLoop.h"
#include "../functions/mainMenuLoop.h"
#include "../functions/settingsLoop.h"
#include "../functions/clockLoop.h"
#include "../functions/batteryLoop.h"
#include "../functions/brightnessLoop.h"
#include "../functions/rotationLoop.h"
#include "../functions/statusBarLoop.h"
#include "../functions/wifiApLoop.h"
#include "../functions/colorsLoop.h"
#include "../functions/wifiScanLoop.h"
#include "../functions/wifiDeauthLoop.h"
#include "../functions/settingsStatusBarLoop.h"
#include "../functions/toggleStatusBarLoop.h"
#include "../functions/toggleStatusBarPidLoop.h"
#include "../functions/toggleStatusBarBatteryLoop.h"
#include "../functions/selectedWifiMenuLoop.h"
#include "../functions/wifiInfoLoop.h"
#include "../functions/wifiMenuLoop.h"
#include "../functions/bluetoothMenuLoop.h"
#include "../functions/bluetoothShutterLoop.h"
#include "../functions/fontsLoop.h"
#include "../functions/levelToolLoop.h"

#include "../functions/settings/toggleStartupSound.h"

#include "../functions/nfc/nfcMenuLoop.h"
#include "../functions/nfc/nfcReadLoop.h"
#include "../functions/nfc/nfcWriteLoop.h"


#include "../functions/flashlight/flashLightMenuLoop.h"
#include "../functions/flashlight/flashLightLoop.h"
#include "../functions/flashlight/flashLightFlickerLoop.h"

#include "../functions/soundLevelLoop.h"